# Generated by Django 2.2.6 on 2019-11-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=150)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Museum')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Location')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Museum')),
                ('sensortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.SensorType')),
            ],
        ),
    ]
