# Generated by Django 2.2.6 on 2019-11-26 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_location_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(null=True, upload_to='data-files/%Y/%m/%d/')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Submission')),
            ],
        ),
    ]
