# Generated by Django 2.2.7 on 2019-12-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191112_1537'),
        ('tracker', '0003_datapoint_submission'),
    ]

    operations = [
    ]
