# Generated by Django 2.2.7 on 2019-12-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_institution'),
        ('tracker', '0004_merge_20191203_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Museum',
            new_name='Institution',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='institution',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='museum',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='blank', help_text='Please give your sensor a unique name to distinguish it from other sensors you may have', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='room',
            field=models.CharField(default='blank', help_text='Please describe the location of your sensor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload',
            field=models.FileField(default='blank', upload_to='data-files/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
