# Generated by Django 2.2.7 on 2019-12-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20191206_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Submission'),
        ),
    ]
